services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
    restart: unless-stopped
    volumes:
      - ./n8n_data:/home/node/.n8n # Descomente para persistência local
    
    networks:
      - default

networks:
  default:
    driver: bridge  
